# ===============================
# Application
# ===============================
spring.application.name=sih2026


# ===============================
# PostgreSQL Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/sih2026
spring.datasource.username=postgres
spring.datasource.password=YOUR_POSTGRES_PASSWORD


# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# Session
# ===============================
server.servlet.session.timeout=30d


# ===============================
# Thymeleaf
# ===============================
spring.thymeleaf.cache=false