# ===============================
# Application
# ===============================

spring.application.name=sih2026
server.address=0.0.0.0
server.port=8080

# ===============================
# PostgreSQL Database
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/sih2026
spring.datasource.username=username
spring.datasource.password=password

# ===============================
# JPA / Hibernate
# ===============================

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Session
# ===============================

server.servlet.session.timeout=30d

# ===============================
# Thymeleaf
# ===============================

spring.thymeleaf.cache=false

# ===============================
# Docker compose
# ===============================

spring.docker.compose.enabled=false

# ===============================
# Model URL
# ===============================

coding_tool.url=http://127.0.0.1:9000
rag_tool.url=http://127.0.0.1:9000


#logging.level.org.springframework.security=TRACE